# Generated by Django 5.0.3 on 2024-04-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Siparisno', models.CharField(max_length=25)),
                ('Pazaryeri', models.CharField(max_length=25)),
                ('Tarih', models.DateField()),
                ('Stokkodu', models.CharField(max_length=20)),
                ('Adet', models.IntegerField()),
                ('Satisfiyati', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Toplam', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Komisyon', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Kargo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Hibedeli', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Isbedeli', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Kalan', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['Siparisno'],
            },
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Afaturano', models.CharField(max_length=20)),
                ('Stokkodu', models.CharField(max_length=20)),
                ('Adet', models.IntegerField()),
                ('Alisfiyati', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Toplam', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['Stokkodu'],
            },
        ),
    ]
