# Generated by Django 5.0.3 on 2024-05-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firma_adi', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Sifre', models.CharField(max_length=25)),
                ('Slug', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
