# Generated by Django 5.0.3 on 2024-04-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stokkodu', models.CharField(max_length=20)),
                ('Adet', models.IntegerField()),
                ('Alisfiyati', models.IntegerField()),
                ('Afaturano', models.TextField()),
            ],
            options={
                'ordering': ['Stokkodu'],
            },
        ),
        migrations.DeleteModel(
            name='Emutablo',
        ),
    ]
