# Generated by Django 5.0.3 on 2024-04-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0002_stok_delete_emutablo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stok',
            name='Alisfiyati',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
