# Generated by Django 5.0.3 on 2024-05-07 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0003_delete_kullanici_stok_firmaadi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siparis',
            name='Hibedeli',
        ),
        migrations.RemoveField(
            model_name='siparis',
            name='Isbedeli',
        ),
        migrations.RemoveField(
            model_name='siparis',
            name='Kalan',
        ),
        migrations.RemoveField(
            model_name='siparis',
            name='Kargo',
        ),
        migrations.AddField(
            model_name='siparis',
            name='Komisyontutari',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stok',
            name='Firmaadi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
