# Generated by Django 5.0.3 on 2024-04-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0003_alter_stok_alisfiyati'),
    ]

    operations = [
        migrations.AddField(
            model_name='stok',
            name='Toplam',
            field=models.DecimalField(decimal_places=2, default=234, max_digits=10),
            preserve_default=False,
        ),
    ]
