# Generated by Django 5.0.3 on 2024-05-07 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0004_remove_siparis_hibedeli_remove_siparis_isbedeli_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siparis',
            name='Firmaadi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='Komisyontutari',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
