# Generated by Django 5.0.3 on 2024-04-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0004_stok_toplam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stok',
            name='Afaturano',
            field=models.CharField(max_length=20),
        ),
    ]
