# Generated by Django 5.0.3 on 2024-06-22 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0005_siparis_firmaadi_alter_siparis_komisyontutari'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Baslik', models.TextField()),
                ('Metin', models.TextField()),
                ('Url', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['Baslik'],
            },
        ),
        migrations.AlterModelOptions(
            name='siparis',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='stok',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='siparis',
            name='Firmaadi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='Stokkodu',
            field=models.CharField(max_length=25),
        ),
    ]
