# Generated by Django 5.0.3 on 2024-06-29 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0006_blog_alter_siparis_options_alter_stok_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Desi', models.TextField(blank=True, default='1')),
                ('Kargotutari', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Siparisno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etikom.siparis')),
            ],
            options={
                'ordering': ['Siparisno'],
            },
        ),
    ]
