# Generated by Django 5.0.3 on 2024-06-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0007_kargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='kargo',
            name='Firmaadi',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='kargo',
            name='Desi',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
