# Generated by Django 5.0.3 on 2024-06-30 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0009_alter_kargo_firmaadi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='kargo',
            name='Firmaadi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kargo',
            name='Siparisno',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
