# Generated by Django 5.0.3 on 2024-07-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0010_alter_kargo_firmaadi_alter_kargo_siparisno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kargo',
            name='Desi',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='Adet',
            field=models.PositiveIntegerField(),
        ),
    ]
