# Generated by Django 5.0.3 on 2024-07-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0011_alter_kargo_desi_alter_siparis_adet'),
    ]

    operations = [
        migrations.AddField(
            model_name='kargo',
            name='Hizmetbedeli',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='kargo',
            name='Toplam',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
