# Generated by Django 5.0.3 on 2024-08-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0012_kargo_hizmetbedeli_kargo_toplam'),
    ]

    operations = [
        migrations.AddField(
            model_name='stok',
            name='Tur',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
