# Generated by Django 5.0.3 on 2024-08-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0013_stok_tur'),
    ]

    operations = [
        migrations.AddField(
            model_name='kargo',
            name='Tur',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='siparis',
            name='Tur',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
