# Generated by Django 5.0.3 on 2024-08-13 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0015_iade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iade',
            old_name='Kargotutari',
            new_name='Iadetutari',
        ),
    ]
