# Generated by Django 5.0.3 on 2024-09-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0016_rename_kargotutari_iade_iadetutari'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iade',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='kargo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='siparis',
            name='Adet',
            field=models.IntegerField(),
        ),
    ]
