# Generated by Django 5.0.3 on 2024-09-05 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0018_kargo_stokkodu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Baslik', models.TextField()),
                ('Tarih', models.DateField()),
                ('Tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Firmaadi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Baslik'],
            },
        ),
    ]
