# Generated by Django 5.0.3 on 2025-09-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0019_gider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gider',
            options={'ordering': ['-Tarih']},
        ),
        migrations.AddField(
            model_name='kargo',
            name='Islembedeli',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
