# Generated by Django 5.0.3 on 2025-09-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0020_alter_gider_options_kargo_islembedeli'),
    ]

    operations = [
        migrations.AddField(
            model_name='stok',
            name='Alistarihi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
