# Generated by Django 5.0.3 on 2025-09-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0021_stok_alistarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gider',
            name='Tarih',
            field=models.DateField(blank=True, null=True),
        ),
    ]
