# Generated by Django 5.0.3 on 2025-09-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0022_alter_gider_tarih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siparis',
            name='Tarih',
            field=models.DateField(blank=True, null=True),
        ),
    ]
