# Generated by Django 5.0.3 on 2025-09-10 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0023_alter_siparis_tarih'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faturakontrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pazaryeri', models.CharField(blank=True, max_length=50, null=True)),
                ('Siparisno', models.CharField(max_length=50)),
                ('Stokkodu', models.CharField(max_length=50)),
                ('Siparisadet', models.IntegerField(blank=True, null=True)),
                ('Satisfiyati', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Toplamsatistutari', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Pazaryeriindirimi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Komisyonorani', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Komisyontutari', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Alisfiyati', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Alistoplami', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Kargodesi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Kargotutari', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Hizmetbedeli', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Islembedeli', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Iadedesi', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Iadetutari', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Kalan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Firmaadi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
