# Generated by Django 5.0.3 on 2025-09-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0024_faturakontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturakontrol',
            name='Tarih',
            field=models.DateField(blank=True, null=True),
        ),
    ]
