# Generated by Django 5.0.3 on 2025-09-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0025_faturakontrol_tarih'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturakontrol',
            name='Iadeadet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
