# Generated by Django 5.0.3 on 2025-09-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etikom', '0026_faturakontrol_iadeadet'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturakontrol',
            name='Adet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
